/**
 * KHELL Horse — Demo Yarış Verisi
 * Gerçek entegrasyonda bu dosya API'dan beslenir.
 */

const DEMO_RACES = [
  {
    raceNo: 1,
    raceName: "1. Koşu",
    time: "13:00",
    track: "İstanbul Veliefendi",
    surface: "çim",
    distance: 1200,
    category: "Maiden",
    horses: [
      {
        number: 1, name: "KARA ŞİMŞEK", jockey: "M. Demir", trainer: "A. Karataş",
        weight: 58, age: 4, agf: 2.1, odds: 2.50, isFavorite: true,
        lastRuns: [2, 1, 3, 1, 2], surface: "çim", preferredSurface: "çim",
        distance: 1200, preferredDistanceMin: 1000, preferredDistanceMax: 1400,
        jockeyWinRate: 22, trainerWinRate: 18,
      },
      {
        number: 2, name: "ALTIN KANAT", jockey: "S. Yılmaz", trainer: "F. Arslan",
        weight: 55, age: 3, agf: 5.8, odds: 7.20, isFavorite: false,
        lastRuns: [4, 3, 2, 2, 1], surface: "çim", preferredSurface: "çim",
        distance: 1200, preferredDistanceMin: 1200, preferredDistanceMax: 1600,
        jockeyWinRate: 15, trainerWinRate: 14,
      },
      {
        number: 3, name: "FIRTINA GÜLÜ", jockey: "H. Kaya", trainer: "B. Şahin",
        weight: 54, age: 4, agf: 4.2, odds: 11.50, isFavorite: false,
        lastRuns: [6, 5, 4, 3, 1], surface: "çim", preferredSurface: "çim",
        distance: 1200, preferredDistanceMin: 1000, preferredDistanceMax: 1200,
        jockeyWinRate: 12, trainerWinRate: 10,
      },
      {
        number: 4, name: "ALBAY", jockey: "C. Türkmen", trainer: "N. Güneş",
        weight: 57, age: 5, agf: 8.5, odds: 18.00, isFavorite: false,
        lastRuns: [5, 4, 6, 4, 3], surface: "çim", preferredSurface: "kum",
        distance: 1200, preferredDistanceMin: 1000, preferredDistanceMax: 1200,
        jockeyWinRate: 9, trainerWinRate: 7,
      },
      {
        number: 5, name: "DENIZCI", jockey: "E. Toprak", trainer: "K. Aydın",
        weight: 56, age: 4, agf: 3.9, odds: 9.80, isFavorite: false,
        lastRuns: [3, 2, 1, 4, 2], surface: "çim", preferredSurface: "çim",
        distance: 1200, preferredDistanceMin: 1200, preferredDistanceMax: 1400,
        jockeyWinRate: 17, trainerWinRate: 13,
      },
      {
        number: 6, name: "RAHAT OLL", jockey: "A. Çelik", trainer: "T. Koç",
        weight: 53, age: 3, agf: 4.5, odds: 14.80, isFavorite: false,
        lastRuns: [7, 5, 3, 2, 1], surface: "çim", preferredSurface: "çim",
        distance: 1200, preferredDistanceMin: 1000, preferredDistanceMax: 1200,
        jockeyWinRate: 18, trainerWinRate: 12,
      },
    ],
  },
  {
    raceNo: 2,
    raceName: "2. Koşu",
    time: "13:45",
    track: "İstanbul Veliefendi",
    surface: "çim",
    distance: 1400,
    category: "Handikap",
    horses: [
      {
        number: 1, name: "KARABAŞ", jockey: "M. Demir", trainer: "A. Karataş",
        weight: 60, age: 6, agf: 1.9, odds: 1.90, isFavorite: true,
        lastRuns: [1, 1, 2, 1, 3], surface: "çim", preferredSurface: "çim",
        distance: 1400, preferredDistanceMin: 1200, preferredDistanceMax: 1600,
        jockeyWinRate: 22, trainerWinRate: 18,
      },
      {
        number: 2, name: "SAFKAN RÜZGAR", jockey: "İ. Bulut", trainer: "S. Keskin",
        weight: 55, age: 5, agf: 5.1, odds: 13.50, isFavorite: false,
        lastRuns: [5, 3, 2, 1, 1], surface: "çim", preferredSurface: "çim",
        distance: 1400, preferredDistanceMin: 1400, preferredDistanceMax: 1800,
        jockeyWinRate: 14, trainerWinRate: 16,
      },
      {
        number: 3, name: "YILDIRIM BEY", jockey: "O. Sağlam", trainer: "H. Özkan",
        weight: 56, age: 5, agf: 6.3, odds: 8.40, isFavorite: false,
        lastRuns: [4, 2, 3, 2, 1], surface: "çim", preferredSurface: "çim",
        distance: 1400, preferredDistanceMin: 1200, preferredDistanceMax: 1600,
        jockeyWinRate: 16, trainerWinRate: 12,
      },
      {
        number: 4, name: "SİYAH İNCİ", jockey: "Y. Doğan", trainer: "C. Altın",
        weight: 54, age: 4, agf: 4.7, odds: 22.00, isFavorite: false,
        lastRuns: [6, 4, 3, 2, 1], surface: "çim", preferredSurface: "kum",
        distance: 1400, preferredDistanceMin: 1200, preferredDistanceMax: 1400,
        jockeyWinRate: 11, trainerWinRate: 9,
      },
      {
        number: 5, name: "EGE ASLANİ", jockey: "F. Kılıç", trainer: "M. Yıldız",
        weight: 57, age: 7, agf: 9.2, odds: 35.00, isFavorite: false,
        lastRuns: [3, 5, 4, 6, 2], surface: "çim", preferredSurface: "çim",
        distance: 1400, preferredDistanceMin: 1600, preferredDistanceMax: 2000,
        jockeyWinRate: 8, trainerWinRate: 7,
      },
    ],
  },
  {
    raceNo: 3,
    raceName: "3. Koşu",
    time: "14:30",
    track: "İstanbul Veliefendi",
    surface: "kum",
    distance: 1600,
    category: "Grup 3",
    horses: [
      {
        number: 1, name: "BORÇ HARÇ", jockey: "A. Demir", trainer: "T. Yılmaz",
        weight: 59, age: 5, agf: 3.2, odds: 3.80, isFavorite: true,
        lastRuns: [2, 2, 1, 3, 2], surface: "kum", preferredSurface: "kum",
        distance: 1600, preferredDistanceMin: 1400, preferredDistanceMax: 1800,
        jockeyWinRate: 20, trainerWinRate: 17,
      },
      {
        number: 2, name: "AKINCI TÜRK", jockey: "B. Çelik", trainer: "R. Arslan",
        weight: 56, age: 4, agf: 4.8, odds: 12.00, isFavorite: false,
        lastRuns: [3, 1, 2, 1, 1], surface: "kum", preferredSurface: "kum",
        distance: 1600, preferredDistanceMin: 1600, preferredDistanceMax: 2000,
        jockeyWinRate: 19, trainerWinRate: 15,
      },
      {
        number: 3, name: "MAVI DALGA", jockey: "C. Toprak", trainer: "D. Koç",
        weight: 55, age: 4, agf: 5.5, odds: 9.50, isFavorite: false,
        lastRuns: [4, 3, 2, 2, 1], surface: "kum", preferredSurface: "kum",
        distance: 1600, preferredDistanceMin: 1400, preferredDistanceMax: 1600,
        jockeyWinRate: 14, trainerWinRate: 11,
      },
      {
        number: 4, name: "GÜN BATIMI", jockey: "K. Şahin", trainer: "L. Kurt",
        weight: 54, age: 3, agf: 2.9, odds: 6.80, isFavorite: false,
        lastRuns: [5, 4, 3, 1, 2], surface: "kum", preferredSurface: "çim",
        distance: 1600, preferredDistanceMin: 1400, preferredDistanceMax: 1800,
        jockeyWinRate: 13, trainerWinRate: 12,
      },
      {
        number: 5, name: "RÜZGAR GÜLÜ", jockey: "E. Aydın", trainer: "P. Arslan",
        weight: 57, age: 5, agf: 7.1, odds: 16.50, isFavorite: false,
        lastRuns: [6, 3, 1, 2, 1], surface: "kum", preferredSurface: "kum",
        distance: 1600, preferredDistanceMin: 1600, preferredDistanceMax: 2000,
        jockeyWinRate: 16, trainerWinRate: 14,
      },
      {
        number: 6, name: "KARINCA", jockey: "M. Güneş", trainer: "S. Özkan",
        weight: 53, age: 4, agf: 8.9, odds: 28.00, isFavorite: false,
        lastRuns: [7, 6, 5, 4, 2], surface: "kum", preferredSurface: "kum",
        distance: 1600, preferredDistanceMin: 1400, preferredDistanceMax: 1600,
        jockeyWinRate: 10, trainerWinRate: 8,
      },
    ],
  },
  {
    raceNo: 4,
    raceName: "4. Koşu",
    time: "15:15",
    track: "İstanbul Veliefendi",
    surface: "çim",
    distance: 1800,
    category: "Maiden",
    horses: [
      {
        number: 1, name: "ASLAN PAY", jockey: "S. Kaya", trainer: "F. Bulut",
        weight: 56, age: 3, agf: 3.5, odds: 4.20, isFavorite: true,
        lastRuns: [1, 3, 2, 4, 1], surface: "çim", preferredSurface: "çim",
        distance: 1800, preferredDistanceMin: 1600, preferredDistanceMax: 2000,
        jockeyWinRate: 18, trainerWinRate: 15,
      },
      {
        number: 2, name: "DAĞIN KARTALII", jockey: "T. Özcan", trainer: "V. Çınar",
        weight: 54, age: 4, agf: 6.2, odds: 11.00, isFavorite: false,
        lastRuns: [4, 2, 1, 2, 1], surface: "çim", preferredSurface: "çim",
        distance: 1800, preferredDistanceMin: 1600, preferredDistanceMax: 2200,
        jockeyWinRate: 15, trainerWinRate: 13,
      },
      {
        number: 3, name: "TITAN", jockey: "A. Sağlam", trainer: "G. Kara",
        weight: 57, age: 5, agf: 4.1, odds: 7.60, isFavorite: false,
        lastRuns: [3, 1, 1, 3, 2], surface: "çim", preferredSurface: "çim",
        distance: 1800, preferredDistanceMin: 1800, preferredDistanceMax: 2400,
        jockeyWinRate: 17, trainerWinRate: 14,
      },
      {
        number: 4, name: "SARI KAPLAN", jockey: "N. Doğan", trainer: "M. Ateş",
        weight: 55, age: 4, agf: 5.9, odds: 19.50, isFavorite: false,
        lastRuns: [5, 4, 3, 1, 2], surface: "çim", preferredSurface: "kum",
        distance: 1800, preferredDistanceMin: 1600, preferredDistanceMax: 1800,
        jockeyWinRate: 12, trainerWinRate: 10,
      },
      {
        number: 5, name: "BEY ATLISI", jockey: "R. Yıldız", trainer: "C. Şahin",
        weight: 58, age: 6, agf: 8.3, odds: 14.00, isFavorite: false,
        lastRuns: [2, 3, 2, 1, 1], surface: "çim", preferredSurface: "çim",
        distance: 1800, preferredDistanceMin: 1600, preferredDistanceMax: 2000,
        jockeyWinRate: 14, trainerWinRate: 12,
      },
    ],
  },
  {
    raceNo: 5,
    raceName: "5. Koşu",
    time: "16:00",
    track: "İstanbul Veliefendi",
    surface: "çim",
    distance: 1000,
    category: "Sprint",
    horses: [
      {
        number: 1, name: "HIZLI RÜZGAR", jockey: "M. Demir", trainer: "K. Aydın",
        weight: 57, age: 4, agf: 2.3, odds: 2.20, isFavorite: true,
        lastRuns: [1, 1, 2, 1, 1], surface: "çim", preferredSurface: "çim",
        distance: 1000, preferredDistanceMin: 800, preferredDistanceMax: 1200,
        jockeyWinRate: 22, trainerWinRate: 19,
      },
      {
        number: 2, name: "ŞIMŞEK ALI", jockey: "B. Toprak", trainer: "H. Aslan",
        weight: 55, age: 3, agf: 5.4, odds: 10.50, isFavorite: false,
        lastRuns: [3, 2, 1, 1, 2], surface: "çim", preferredSurface: "çim",
        distance: 1000, preferredDistanceMin: 1000, preferredDistanceMax: 1200,
        jockeyWinRate: 16, trainerWinRate: 13,
      },
      {
        number: 3, name: "LEOPAR", jockey: "O. Kılıç", trainer: "S. Bulut",
        weight: 54, age: 5, agf: 4.6, odds: 8.00, isFavorite: false,
        lastRuns: [4, 3, 2, 2, 1], surface: "çim", preferredSurface: "çim",
        distance: 1000, preferredDistanceMin: 800, preferredDistanceMax: 1000,
        jockeyWinRate: 13, trainerWinRate: 11,
      },
      {
        number: 4, name: "GECE YILDIZI", jockey: "Y. Çelik", trainer: "F. Özkan",
        weight: 56, age: 4, agf: 7.8, odds: 24.00, isFavorite: false,
        lastRuns: [5, 4, 2, 1, 2], surface: "çim", preferredSurface: "çim",
        distance: 1000, preferredDistanceMin: 1000, preferredDistanceMax: 1400,
        jockeyWinRate: 11, trainerWinRate: 9,
      },
      {
        number: 5, name: "TATLI BADEM", jockey: "E. Sağlam", trainer: "P. Kara",
        weight: 53, age: 3, agf: 3.8, odds: 6.50, isFavorite: false,
        lastRuns: [6, 3, 1, 2, 1], surface: "çim", preferredSurface: "kum",
        distance: 1000, preferredDistanceMin: 800, preferredDistanceMax: 1000,
        jockeyWinRate: 15, trainerWinRate: 12,
      },
    ],
  },
];

// Geçmiş başarı demo kartları
const DEMO_WINS = [
  { date: "3 Mayıs 2026", race: "İstanbul 4. Koşu", horse: "RÜZGAR BEY", odds: 12.50, result: "1.", label: "KHELL yakaladı" },
  { date: "1 Mayıs 2026", race: "Bursa 2. Koşu", horse: "KARANLIK PRENS", odds: 8.20, result: "1.", label: "KHELL yakaladı" },
  { date: "29 Nisan 2026", race: "Ankara 3. Koşu", horse: "SİYAH ELMAS", odds: 18.00, result: "1.", label: "KHELL fırsat gördü" },
  { date: "27 Nisan 2026", race: "İzmir 5. Koşu", horse: "TATLI RÜZGAR", odds: 9.60, result: "1.", label: "KHELL yakaladı" },
  { date: "25 Nisan 2026", race: "İstanbul 1. Koşu", horse: "ALTIN KANAT", odds: 14.30, result: "1.", label: "KHELL işaretledi" },
  { date: "23 Nisan 2026", race: "Bursa 6. Koşu", horse: "MAVIŞ", odds: 22.00, result: "1.", label: "KHELL sürpriz gördü" },
];
